import { FactDefinition } from '../types/expert-system';

export const KNOWLEDGE_BASE_FACTS: FactDefinition[] = [
  // Core Symptoms
  {
    id: 'F001',
    key: 'fever',
    name: 'Fever (Elevated Temperature)',
    category: 'symptom',
    description: 'Oral/tympanic body temperature exceeding 37.8°C (100.0°F).',
    type: 'boolean',
  },
  {
    id: 'F002',
    key: 'cough',
    name: 'Cough',
    category: 'symptom',
    description: 'Dry or productive reflex cough clearing the respiratory airways.',
    type: 'boolean',
  },
  {
    id: 'F003',
    key: 'sore_throat',
    name: 'Sore Throat (Pharyngitis)',
    category: 'symptom',
    description: 'Pain, scratchiness, or irritation of the throat that often worsens when swallowing.',
    type: 'boolean',
  },
  {
    id: 'F004',
    key: 'headache',
    name: 'Headache (Cephalea)',
    category: 'symptom',
    description: 'Pain arising from the head or upper neck of the body.',
    type: 'boolean',
  },
  {
    id: 'F005',
    key: 'fatigue',
    name: 'Fatigue / Malaise',
    category: 'symptom',
    description: 'Feeling of overtiredness, low energy, and a strong desire to sleep.',
    type: 'boolean',
  },
  {
    id: 'F006',
    key: 'runny_nose',
    name: 'Rhinorrhea (Runny / Stuffy Nose)',
    category: 'symptom',
    description: 'Excessive nasal discharge or congestion.',
    type: 'boolean',
  },
  {
    id: 'F007',
    key: 'abdominal_pain',
    name: 'Abdominal Pain',
    category: 'symptom',
    description: 'Discomfort or pain anywhere between the chest and groin.',
    type: 'boolean',
  },
  {
    id: 'F008',
    key: 'vomiting',
    name: 'Vomiting / Emesis',
    category: 'symptom',
    description: 'Involuntary, forceful expulsion of the contents of stomach through mouth.',
    type: 'boolean',
  },
  {
    id: 'F009',
    key: 'diarrhea',
    name: 'Diarrhea',
    category: 'symptom',
    description: 'Frequent passage of loose, watery stools (> 3 episodes in 24 hours).',
    type: 'boolean',
  },
  {
    id: 'F010',
    key: 'dizziness',
    name: 'Dizziness / Lightheadedness',
    category: 'symptom',
    description: 'Impairment in spatial perception and stability, feeling faint or unsteady.',
    type: 'boolean',
  },
  {
    id: 'F011',
    key: 'shortness_of_breath',
    name: 'Shortness of Breath (Dyspnea)',
    category: 'symptom',
    description: 'Subjective experience of breathing discomfort or difficulty catching breath.',
    type: 'boolean',
    isRedFlag: true,
  },
  {
    id: 'F012',
    key: 'chest_pain',
    name: 'Chest Pain or Pressure',
    category: 'warning_sign',
    description: 'Substernal pressure, squeezing, tightness, or sharp thoracic pain.',
    type: 'boolean',
    isRedFlag: true,
  },
  {
    id: 'F013',
    key: 'stiff_neck',
    name: 'Stiff Neck (Nuchal Rigidity)',
    category: 'warning_sign',
    description: 'Inability to flex the neck forward due to rigidity of the neck muscles; sign of meningeal irritation.',
    type: 'boolean',
    isRedFlag: true,
  },
  {
    id: 'F014',
    key: 'high_fever',
    name: 'High Fever (>39.5°C / 103.1°F)',
    category: 'vitals',
    description: 'Severe hyperpyrexia posing increased risk for systemic complications.',
    type: 'boolean',
  },
  {
    id: 'F015',
    key: 'blood_in_stool_or_vomit',
    name: 'Blood in Stool or Vomitus (Hematemesis / Melena)',
    category: 'warning_sign',
    description: 'Visible red blood or coffee-ground material indicating gastrointestinal bleeding.',
    type: 'boolean',
    isRedFlag: true,
  },
  {
    id: 'F016',
    key: 'confusion',
    name: 'Altered Mental Status / Confusion',
    category: 'warning_sign',
    description: 'Disorientation, lethargy, incoherent speech, or sudden memory deficit.',
    type: 'boolean',
    isRedFlag: true,
  },
  {
    id: 'F017',
    key: 'sudden_weakness',
    name: 'Sudden Weakness or Numbness (Facial Droop / Arm Weakness)',
    category: 'warning_sign',
    description: 'Unilateral motor or sensory loss consistent with acute cerebrovascular accident (Stroke FAST).',
    type: 'boolean',
    isRedFlag: true,
  },
  {
    id: 'F018',
    key: 'skin_rash',
    name: 'Skin Rash or Petechiae',
    category: 'symptom',
    description: 'Erythematous eruption, purpura, or non-blanching petechial spots.',
    type: 'boolean',
  },
  {
    id: 'F019',
    key: 'ear_pain',
    name: 'Ear Pain (Otalgia)',
    category: 'symptom',
    description: 'Throbbing, sharp, or dull ache localized in the auditory canal or middle ear.',
    type: 'boolean',
  },
  {
    id: 'F020',
    key: 'body_aches',
    name: 'Myalgia / Body Aches',
    category: 'symptom',
    description: 'Diffuse muscle aches, soreness, or back/limb aching characteristic of viral infection.',
    type: 'boolean',
  },
  {
    id: 'F021',
    key: 'loss_of_taste_smell',
    name: 'Anosmia / Ageusia (Loss of Smell or Taste)',
    category: 'symptom',
    description: 'Sudden reduction or total absence of olfactory or gustatory sensation.',
    type: 'boolean',
  },
  {
    id: 'F022',
    key: 'wheezing',
    name: 'Audible Wheezing / Stridor',
    category: 'warning_sign',
    description: 'High-pitched whistling sound during breathing caused by narrowed airways.',
    type: 'boolean',
  },
  {
    id: 'F023',
    key: 'severe_localized_pain',
    name: 'Severe Localized Right Lower Quadrant Pain',
    category: 'warning_sign',
    description: 'Sharp focal tenderness in the right iliac fossa (McBurney point) suspicious for acute appendicitis.',
    type: 'boolean',
  },

  // Duration Facts
  {
    id: 'F040',
    key: 'duration_acute',
    name: 'Acute Duration (<= 3 days)',
    category: 'duration',
    description: 'Symptoms began within the last 72 hours.',
    type: 'boolean',
  },
  {
    id: 'F041',
    key: 'duration_subacute',
    name: 'Subacute Duration (4 to 7 days)',
    category: 'duration',
    description: 'Symptoms present for 4 to 7 days.',
    type: 'boolean',
  },
  {
    id: 'F042',
    key: 'duration_persistent',
    name: 'Persistent Symptoms (> 7 days)',
    category: 'duration',
    description: 'Symptoms extending beyond normal self-limiting viral timeframes (> 1 week).',
    type: 'boolean',
  },
  {
    id: 'F043',
    key: 'duration_chronic',
    name: 'Chronic Symptoms (> 14 days)',
    category: 'duration',
    description: 'Long-standing continuous or relapsing symptomatology.',
    type: 'boolean',
  },

  // Severity Facts
  {
    id: 'F050',
    key: 'severity_mild',
    name: 'Mild Severity',
    category: 'severity',
    description: 'Noticeable symptoms that do not disrupt normal daily activities or work.',
    type: 'boolean',
  },
  {
    id: 'F051',
    key: 'severity_moderate',
    name: 'Moderate Severity',
    category: 'severity',
    description: 'Symptoms disrupt sleep or daily tasks, requiring rest and relief measures.',
    type: 'boolean',
  },
  {
    id: 'F052',
    key: 'severity_severe',
    name: 'Severe Severity',
    category: 'severity',
    description: 'Incapacitating symptoms preventing normal mobility or self-care.',
    type: 'boolean',
  },

  // Patient Demographics & Modifiers
  {
    id: 'F060',
    key: 'age_infant',
    name: 'Infant / Young Child (< 2 years old)',
    category: 'demographic',
    description: 'Pediatric age group with higher vulnerability to rapid dehydration and systemic infection.',
    type: 'boolean',
  },
  {
    id: 'F061',
    key: 'age_elderly',
    name: 'Elderly Adult (>= 65 years old)',
    category: 'demographic',
    description: 'Geriatric patient group prone to atypical presentations and complications.',
    type: 'boolean',
  },
  {
    id: 'F062',
    key: 'is_pregnant',
    name: 'Active Pregnancy',
    category: 'comorbidity',
    description: 'Altered hemodynamics, teratogenic drug restrictions, and maternal-fetal considerations.',
    type: 'boolean',
  },
  {
    id: 'F063',
    key: 'has_chronic_disease',
    name: 'Chronic Comorbid Condition',
    category: 'comorbidity',
    description: 'Pre-existing conditions such as diabetes, chronic heart failure, COPD, asthma, or immunocompromise.',
    type: 'boolean',
  },
];

export const CATEGORY_DESCRIPTIONS: Record<string, string> = {
  Respiratory: 'Disorders involving the upper and lower respiratory tracts (nasal passages, throat, bronchi, and lungs).',
  Cardiovascular: 'Conditions affecting cardiac circulation, heart muscle, or vascular integrity. High red-flag sensitivity.',
  Gastrointestinal: 'Digestive tract symptoms spanning stomach, intestines, liver, and biliary tree.',
  Neurological: 'Central and peripheral nervous system symptoms including intracranial pressure, vascular events, or migraines.',
  Systemic: 'Generalized systemic infections or inflammatory states characterized by fever, malaise, or multi-organ involvement.',
  Dermatological: 'Cutaneous presentations, exanthems, petechial rashes, and associated hypersensitivities.',
};
