import { NutrientProfile } from '../types/nutrition';

export const NUTRITION_KNOWLEDGE_BASE: NutrientProfile[] = [
  {
    id: 'vitamin-b12',
    name: 'Vitamin B12',
    chemicalName: 'Cobalamin',
    aliases: [
      'b12',
      'b-12',
      'b 12',
      'vitamin b12',
      'vitaminb12',
      'vitamineb12',
      'vitamine b12',
      'vitamine-b12',
      'vit b12',
      'vitb12',
      'cobalamin',
      'cyanocobalamin',
      'methylcobalamin',
    ],
    type: 'vitamin',
    whatItDoesInBody: [
      'Red Blood Cell Synthesis: Crucial cofactor for erythropoiesis; prevents megaloblastic (pernicious) anemia by enabling cell division.',
      'Neurological Protection: Maintains myelin sheaths that insulate and protect nerve fibers throughout the brain and spinal cord.',
      'DNA & Cellular Energy: Acts as a coenzyme in fatty acid and amino acid metabolism, powering mitochondrial energy production.',
      'Homocysteine Regulation: Converts homocysteine into methionine alongside folate, protecting cardiovascular and endothelial health.',
    ],
    rdaAdults: '2.4 mcg/day for healthy adults (2.6 mcg during pregnancy, 2.8 mcg during lactation)',
    deficiencyRisks: [
      'Pernicious / Megaloblastic Anemia: Fatigue, weakness, pale jaundice skin, and shortness of breath.',
      'Neuropathy & Nerve Damage: Symmetrical tingling or numbness (pins-and-needles) in hands and feet.',
      'Cognitive & Mood Disturbances: Memory decline, brain fog, confusion, depression, and loss of balance.',
      'Glossitis: Painful, swollen, inflamed, smooth red tongue.',
    ],
    foodSourcesSorted: [
      {
        name: 'Cooked Clams',
        serving: '100g (3.5 oz)',
        amount: '98.9 mcg',
        dailyValuePercentage: 4120,
        category: 'seafood',
        dietaryTags: ['pescatarian', 'omnivore', 'gluten_free'],
        notes: 'The single densest dietary source of bioavailable cobalamin.',
      },
      {
        name: 'Beef Liver (Cooked, Braised)',
        serving: '100g (3.5 oz)',
        amount: '70.6 mcg',
        dailyValuePercentage: 2940,
        category: 'meat',
        dietaryTags: ['omnivore', 'gluten_free'],
        notes: 'Organ meats store the highest concentrations of B12 in animal physiology.',
      },
      {
        name: 'Fortified Nutritional Yeast',
        serving: '2 tablespoons (15g)',
        amount: '17.6 mcg',
        dailyValuePercentage: 730,
        category: 'plant_based',
        dietaryTags: ['vegan', 'vegetarian', 'gluten_free'],
        notes: 'Gold standard plant-based source fortified with active methyl/cyanocobalamin.',
      },
      {
        name: 'Atlantic Mackerel (Cooked)',
        serving: '100g (3.5 oz)',
        amount: '19.0 mcg',
        dailyValuePercentage: 790,
        category: 'seafood',
        dietaryTags: ['pescatarian', 'omnivore', 'gluten_free'],
        notes: 'High in both B12 and anti-inflammatory Omega-3 EPA/DHA fatty acids.',
      },
      {
        name: 'Sardines (Canned in Oil/Water)',
        serving: '1 can (100g)',
        amount: '8.9 mcg',
        dailyValuePercentage: 370,
        category: 'seafood',
        dietaryTags: ['pescatarian', 'omnivore', 'gluten_free'],
        notes: 'Also supplies calcium and vitamin D.',
      },
      {
        name: 'Wild Atlantic Salmon (Cooked)',
        serving: '100g (3.5 oz fillet)',
        amount: '3.2 mcg',
        dailyValuePercentage: 133,
        category: 'seafood',
        dietaryTags: ['pescatarian', 'omnivore', 'gluten_free'],
        notes: 'Clean lean protein with optimal digestive absorption.',
      },
      {
        name: 'Lean Ground Beef (85/15, Cooked)',
        serving: '100g (3.5 oz)',
        amount: '2.6 mcg',
        dailyValuePercentage: 108,
        category: 'meat',
        dietaryTags: ['omnivore', 'gluten_free'],
        notes: 'Easily meets 100% of daily adult requirement in a single standard meal.',
      },
      {
        name: 'Fortified Plant Milk (Soy / Almond / Oat)',
        serving: '1 cup (240ml)',
        amount: '1.2 - 2.5 mcg',
        dailyValuePercentage: 50,
        category: 'plant_based',
        dietaryTags: ['vegan', 'vegetarian', 'gluten_free'],
        notes: 'Check label for "Cyanocobalamin" or "B12" in ingredients.',
      },
      {
        name: 'Whole Milk / Greek Yogurt',
        serving: '1 cup (245g)',
        amount: '1.1 mcg',
        dailyValuePercentage: 46,
        category: 'dairy',
        dietaryTags: ['vegetarian', 'gluten_free'],
        notes: 'Studies suggest B12 from dairy has superior bioavailability compared to meat.',
      },
      {
        name: 'Large Whole Eggs (Hard-boiled or Poached)',
        serving: '2 whole eggs (100g)',
        amount: '1.1 mcg',
        dailyValuePercentage: 46,
        category: 'dairy',
        dietaryTags: ['vegetarian', 'gluten_free'],
        notes: '90% of the B12 is concentrated inside the egg yolk, not the white.',
      },
    ],
    consumptionAndBioavailabilityAdvice: [
      'Stomach Acid & Intrinsic Factor Requirement: B12 is protein-bound in food. Gastric acid unbinds it, then intrinsic factor (from parietal cells) allows absorption in the terminal ileum.',
      'Absorption Plateau: Intrinsic factor receptors saturate at ~1.5 to 2.0 mcg per meal. Consuming moderate amounts spaced throughout the day yields higher net absorption than one massive dose.',
      'Medication Interferences: Long-term use of PPI antacids (omeprazole), H2 blockers, and Metformin (diabetes) significantly impairs B12 absorption; monitoring levels is advised.',
      'Vegans & Vegetarians: Plant foods do not naturally produce B12 (algae/spirulina contain non-bioavailable pseudovitamin B12). Fortified nutritional yeast or oral supplements are medically mandatory.',
    ],
    interactionTips: [
      'Works synergistically with Folate (Vitamin B9) in 1-carbon metabolism; high folate intake can mask B12 deficiency anemia while nerve damage continues unnoticed.',
      'Alcohol irritates gastric mucosa and depletes hepatic cobalamin storage.',
    ],
  },
  {
    id: 'vitamin-d',
    name: 'Vitamin D',
    chemicalName: 'Cholecalciferol (D3) / Ergocalciferol (D2)',
    aliases: ['vitamin d', 'vitamin d3', 'd3', 'd2', 'sunshine vitamin', 'cholecalciferol'],
    type: 'vitamin',
    whatItDoesInBody: [
      'Calcium & Bone Mineralization: Stimulates intestinal absorption of calcium and phosphorus; prevents rickets in children and osteomalacia/osteoporosis in adults.',
      'Immune System Regulation: Modulates T-cell and macrophage response; activates antimicrobial peptides (cathelicidin) to resist respiratory infections.',
      'Neuromuscular Function: Preserves muscle strength and prevents sarcopenia and fall risks.',
      'Gene Transcription: Acts as a steroid hormone receptor ligand affecting hundreds of biological genes.',
    ],
    rdaAdults: '600 - 800 IU/day (15 - 20 mcg), though functional medicine targets 1000 - 2000 IU/day for optimal blood serum (30-50 ng/mL)',
    deficiencyRisks: [
      'Bone pain, muscle cramps, and increased fracture susceptibility (osteopenia/osteoporosis).',
      'Frequent respiratory infections and prolonged illness duration.',
      'Chronic fatigue, lethargy, and seasonal affective depressive disorder (SAD).',
    ],
    foodSourcesSorted: [
      {
        name: 'Cod Liver Oil',
        serving: '1 tablespoon (14g)',
        amount: '1360 IU (34 mcg)',
        dailyValuePercentage: 170,
        category: 'seafood',
        dietaryTags: ['pescatarian', 'omnivore', 'gluten_free'],
        notes: 'Highest natural food source; also rich in Vitamin A and Omega-3.',
      },
      {
        name: 'Sockeye / Wild Salmon (Cooked)',
        serving: '100g (3.5 oz fillet)',
        amount: '570 - 710 IU',
        dailyValuePercentage: 88,
        category: 'seafood',
        dietaryTags: ['pescatarian', 'omnivore', 'gluten_free'],
        notes: 'Wild salmon yields 3-4x more vitamin D than farm-raised varieties.',
      },
      {
        name: 'UV-Exposed Cremini / Portobello Mushrooms',
        serving: '100g (3.5 oz)',
        amount: '400 - 500 IU',
        dailyValuePercentage: 62,
        category: 'plant_based',
        dietaryTags: ['vegan', 'vegetarian', 'gluten_free'],
        notes: 'Contains Ergocalciferol (D2) produced when mushrooms are sun-dried or UV-treated.',
      },
      {
        name: 'Canned Light Tuna in Oil',
        serving: '100g (3.5 oz)',
        amount: '269 IU',
        dailyValuePercentage: 34,
        category: 'seafood',
        dietaryTags: ['pescatarian', 'omnivore', 'gluten_free'],
        notes: 'Convenient pantry staple.',
      },
      {
        name: 'Fortified Cow Milk or Soy Milk',
        serving: '1 cup (240ml)',
        amount: '120 IU',
        dailyValuePercentage: 15,
        category: 'dairy',
        dietaryTags: ['vegetarian', 'gluten_free'],
        notes: 'Standardized fortification program across most countries.',
      },
      {
        name: 'Egg Yolks (Pasture-Raised)',
        serving: '2 whole eggs',
        amount: '88 IU',
        dailyValuePercentage: 11,
        category: 'dairy',
        dietaryTags: ['vegetarian', 'gluten_free'],
        notes: 'Hens raised outdoors with sunlight access provide higher D3 in yolk.',
      },
    ],
    consumptionAndBioavailabilityAdvice: [
      'Fat-Soluble: Must be ingested alongside dietary fats (e.g. olive oil, avocado, whole eggs) to be absorbed efficiently across intestinal micellar pathways.',
      'Cutaneous Synthesis: 15-20 minutes of midday sun exposure (face, arms, legs without sunscreen) synthesizes vitamin D3 naturally in summer months.',
      'Magnesium Synergy: Magnesium is a required cofactor to convert 25(OH)D into active 1,25(OH)2D calcitriol in kidneys.',
    ],
  },
  {
    id: 'iron',
    name: 'Iron',
    chemicalName: 'Ferrous (Fe2+) / Ferric (Fe3+)',
    aliases: ['iron', 'fe', 'ferritin', 'heme iron', 'elemental iron'],
    type: 'mineral',
    whatItDoesInBody: [
      'Oxygen Transport (Hemoglobin): Fundamental core of hemoglobin molecules in red blood cells that shuttle oxygen from lungs to all tissues.',
      'Myoglobin & Muscle Metabolism: Stores oxygen in muscle tissues for physical contraction and sustained endurance.',
      'Enzymatic Energy Production: Central component of cytochrome enzymes in electron transport chain for ATP production.',
      'Neurocognitive Health: Essential for dopamine synthesis and pediatric brain development.',
    ],
    rdaAdults: '8 mg/day for adult men & post-menopausal women; 18 mg/day for pre-menopausal women (27 mg pregnancy)',
    deficiencyRisks: [
      'Iron-Deficiency Anemia: Chronic severe exhaustion, brittle spoon nails (koilonychia), cold hands/feet.',
      'Pallor: Pale conjunctiva inside lower eyelids and pale gums/nailbeds.',
      'Pica: Craving non-food substances like ice, dirt, or chalk.',
      'Restless Leg Syndrome (RLS): Uncomfortable tingling urges to move legs in bed.',
    ],
    foodSourcesSorted: [
      {
        name: 'Cooked Oysters / Clams',
        serving: '100g (3.5 oz)',
        amount: '9.2 mg',
        dailyValuePercentage: 51,
        category: 'seafood',
        dietaryTags: ['pescatarian', 'omnivore', 'gluten_free'],
        notes: 'Highly bioavailable heme iron along with zinc and B12.',
      },
      {
        name: 'Beef / Poultry Liver',
        serving: '100g (3.5 oz)',
        amount: '6.5 mg',
        dailyValuePercentage: 36,
        category: 'meat',
        dietaryTags: ['omnivore', 'gluten_free'],
        notes: 'Dense heme iron that absorbs at 25-35% efficiency.',
      },
      {
        name: 'Cooked Lentils / Black Beans',
        serving: '1 cup (200g)',
        amount: '6.6 mg',
        dailyValuePercentage: 37,
        category: 'plant_based',
        dietaryTags: ['vegan', 'vegetarian', 'gluten_free'],
        notes: 'Excellent non-heme iron source; soak before boiling to reduce phytates.',
      },
      {
        name: 'Pumpkin Seeds (Pepitas, Roasted)',
        serving: '1 oz (28g / 1 handful)',
        amount: '4.2 mg',
        dailyValuePercentage: 23,
        category: 'nut_seed',
        dietaryTags: ['vegan', 'vegetarian', 'gluten_free'],
        notes: 'Also packed with magnesium and zinc.',
      },
      {
        name: 'Firm Tofu (Organic Soy)',
        serving: '1/2 cup (125g)',
        amount: '3.4 mg',
        dailyValuePercentage: 19,
        category: 'plant_based',
        dietaryTags: ['vegan', 'vegetarian', 'gluten_free'],
        notes: 'Versatile plant-based iron & calcium option.',
      },
      {
        name: 'Lean Red Beef (Sirloin/Steak)',
        serving: '100g (3.5 oz)',
        amount: '2.7 mg',
        dailyValuePercentage: 15,
        category: 'meat',
        dietaryTags: ['omnivore', 'gluten_free'],
        notes: 'Standard heme iron reference food.',
      },
      {
        name: 'Cooked Spinach',
        serving: '1 cup cooked (180g)',
        amount: '6.4 mg',
        dailyValuePercentage: 36,
        category: 'vegetable',
        dietaryTags: ['vegan', 'vegetarian', 'gluten_free'],
        notes: 'Contains oxalates which bind iron; cooking/steaming improves bioavailability.',
      },
      {
        name: 'Dark Chocolate (70-85% Cacao)',
        serving: '1 oz (28g)',
        amount: '3.4 mg',
        dailyValuePercentage: 19,
        category: 'plant_based',
        dietaryTags: ['vegan', 'vegetarian', 'gluten_free'],
        notes: 'Rich in polyphenols, copper, and iron.',
      },
    ],
    consumptionAndBioavailabilityAdvice: [
      'Vitamin C Synergy: Pair non-heme iron (beans, spinach, lentils) with Vitamin C (lemon juice, bell peppers, tomatoes) to reduce Fe3+ to Fe2+, multiplying absorption up to 300%.',
      'Inhibitors to Avoid: Avoid drinking tea (tannins), coffee (polyphenols), or taking calcium supplements within 1 hour of iron-rich meals.',
      'Cookware Tip: Cooking acidic foods (tomato sauce) in cast iron skillets increases food iron content.',
    ],
  },
  {
    id: 'magnesium',
    name: 'Magnesium',
    chemicalName: 'Mg2+',
    aliases: ['magnesium', 'mg', 'magnesium glycinate', 'magnesium citrate'],
    type: 'mineral',
    whatItDoesInBody: [
      '300+ Enzymatic Reactions: Essential cofactor for ATP energy storage, glycolysis, and protein synthesis.',
      'Muscle Relaxation & Neurotransmission: Counterbalances calcium in actin-myosin filaments to prevent muscle cramps, spasms, and twitching.',
      'Cardiac Rhythm Stability: Maintains resting membrane potentials in heart myocytes, preventing arrhythmias.',
      'Sleep & GABA Regulation: Binds GABA neurotransmitter receptors to calm nervous system arousal and regulate melatonin.',
    ],
    rdaAdults: '400 - 420 mg/day for adult men; 310 - 320 mg/day for women',
    deficiencyRisks: [
      'Muscle cramps (nocturnal leg cramps), eye eyelid twitching (fasciculations), and tension headaches.',
      'Insomnia, heightened anxiety, and hyper-reactivity to sensory stimuli.',
      'Elevated blood pressure, insulin resistance, and osteopenia.',
    ],
    foodSourcesSorted: [
      {
        name: 'Pumpkin Seeds (Pepitas)',
        serving: '1 oz (28g)',
        amount: '156 mg',
        dailyValuePercentage: 37,
        category: 'nut_seed',
        dietaryTags: ['vegan', 'vegetarian', 'gluten_free'],
        notes: 'Top whole food magnesium density.',
      },
      {
        name: 'Chia Seeds',
        serving: '1 oz (28g)',
        amount: '111 mg',
        dailyValuePercentage: 26,
        category: 'nut_seed',
        dietaryTags: ['vegan', 'vegetarian', 'gluten_free'],
        notes: 'Also supplies soluble fiber and plant Omega-3 ALA.',
      },
      {
        name: 'Almonds (Dry Roasted)',
        serving: '1 oz (23 almonds)',
        amount: '80 mg',
        dailyValuePercentage: 19,
        category: 'nut_seed',
        dietaryTags: ['vegan', 'vegetarian', 'gluten_free'],
        notes: 'High in Vitamin E antioxidant protection.',
      },
      {
        name: 'Boiled Spinach',
        serving: '1/2 cup (90g)',
        amount: '78 mg',
        dailyValuePercentage: 19,
        category: 'vegetable',
        dietaryTags: ['vegan', 'vegetarian', 'gluten_free'],
        notes: 'Magnesium sits at the central ring of chlorophyll molecules.',
      },
      {
        name: 'Black Beans (Cooked)',
        serving: '1 cup (172g)',
        amount: '120 mg',
        dailyValuePercentage: 29,
        category: 'plant_based',
        dietaryTags: ['vegan', 'vegetarian', 'gluten_free'],
        notes: 'Great combined source of fiber and minerals.',
      },
      {
        name: 'Dark Chocolate (85% Cacao)',
        serving: '1 oz (28g)',
        amount: '64 mg',
        dailyValuePercentage: 15,
        category: 'plant_based',
        dietaryTags: ['vegan', 'vegetarian', 'gluten_free'],
        notes: 'Healthy treat that relaxes vascular tone.',
      },
      {
        name: 'Avocado (Medium)',
        serving: '1 whole avocado (200g)',
        amount: '58 mg',
        dailyValuePercentage: 14,
        category: 'fruit',
        dietaryTags: ['vegan', 'vegetarian', 'gluten_free'],
        notes: 'Also delivers 700mg potassium and monounsaturated fats.',
      },
    ],
    consumptionAndBioavailabilityAdvice: [
      'Refined food diets lose up to 80% of magnesium during white flour and sugar processing.',
      'High zinc supplementation (>50mg) can compete with magnesium absorption.',
      'Best consumed across green leafy vegetables, seeds, nuts, and mineral water.',
    ],
  },
  {
    id: 'zinc',
    name: 'Zinc',
    chemicalName: 'Zn2+',
    aliases: ['zinc', 'zn', 'zinc picolinate', 'zinc gluconate'],
    type: 'mineral',
    whatItDoesInBody: [
      'Immune Defense & T-Cell Activation: Powers neutrophils and natural killer cells; halts rhinovirus replication.',
      'Wound Healing & Tissue Repair: Vital for collagen synthesis and cell division in skin and epithelial tissues.',
      'Taste & Smell Acuity (Gustin): Core constituent of salivary enzyme gustin; essential for olfactory reception.',
      'Testosterone & Endocrine Regulation: Maintains reproductive hormone synthesis and thyroid conversion.',
    ],
    rdaAdults: '11 mg/day for adult men; 8 mg/day for adult women (11-12 mg pregnancy)',
    deficiencyRisks: [
      'Impaired immunity with recurrent viral colds and delayed wound closure.',
      'Hypogeusia / Anosmia (loss of taste and smell sensitivity).',
      'Alopecia (hair loss), skin lesions, acne, and white spots on fingernails.',
    ],
    foodSourcesSorted: [
      {
        name: 'Raw / Steamed Oysters',
        serving: '6 medium oysters (84g)',
        amount: '32.0 mg',
        dailyValuePercentage: 290,
        category: 'seafood',
        dietaryTags: ['pescatarian', 'omnivore', 'gluten_free'],
        notes: 'Unrivaled natural zinc concentration in the animal kingdom.',
      },
      {
        name: 'Beef Chuck Roast / Steak',
        serving: '100g (3.5 oz)',
        amount: '8.5 mg',
        dailyValuePercentage: 77,
        category: 'meat',
        dietaryTags: ['omnivore', 'gluten_free'],
        notes: 'Absorbs 2-3x better than plant-based zinc due to absence of phytates.',
      },
      {
        name: 'Crab / Lobster',
        serving: '100g (3.5 oz)',
        amount: '6.5 mg',
        dailyValuePercentage: 59,
        category: 'seafood',
        dietaryTags: ['pescatarian', 'omnivore', 'gluten_free'],
        notes: 'High in zinc, selenium, and copper.',
      },
      {
        name: 'Pumpkin Seeds (Pepitas)',
        serving: '1 oz (28g)',
        amount: '2.2 mg',
        dailyValuePercentage: 20,
        category: 'nut_seed',
        dietaryTags: ['vegan', 'vegetarian', 'gluten_free'],
        notes: 'Excellent plant source; roasting or sprouting neutralizes phytate binding.',
      },
      {
        name: 'Chickpeas / Garbanzo Beans',
        serving: '1 cup cooked (164g)',
        amount: '2.5 mg',
        dailyValuePercentage: 23,
        category: 'plant_based',
        dietaryTags: ['vegan', 'vegetarian', 'gluten_free'],
        notes: 'Hummus or cooked chickpeas.',
      },
      {
        name: 'Cashews',
        serving: '1 oz (28g)',
        amount: '1.6 mg',
        dailyValuePercentage: 15,
        category: 'nut_seed',
        dietaryTags: ['vegan', 'vegetarian', 'gluten_free'],
        notes: 'Delivers copper and zinc together.',
      },
    ],
    consumptionAndBioavailabilityAdvice: [
      'Phytates in unsoaked raw grains/legumes bind zinc; soaking, fermenting, and leavening bread significantly increases zinc release.',
      'Do not exceed 40 mg/day chronic supplemental zinc without copper, as excess zinc induces metallothionein, blocking copper absorption.',
    ],
  },
  {
    id: 'vitamin-c',
    name: 'Vitamin C',
    chemicalName: 'L-Ascorbic Acid',
    aliases: ['vitamin c', 'ascorbic acid', 'ascorbate'],
    type: 'vitamin',
    whatItDoesInBody: [
      'Collagen Biosynthesis: Essential for prolyl and lysyl hydroxylase enzymes that build connective tissue, cartilage, skin, and blood vessel walls.',
      'Master Water-Soluble Antioxidant: Neutralizes reactive oxygen species (ROS) and regenerates oxidized Vitamin E.',
      'Non-Heme Iron Absorption: Reduces ferric iron to soluble ferrous iron in the duodenum.',
      'Immune Phagocyte Enhancement: Stimulates neutrophil migration and protects host cells from oxidative damage during infection.',
    ],
    rdaAdults: '90 mg/day for adult men; 75 mg/day for adult women (+35 mg/day for smokers)',
    deficiencyRisks: [
      'Scurvy: Bleeding gums (gingivitis), corkscrew hairs, petechial hemorrhages under skin, poor wound healing.',
      'Chronic lethargy, joint aching, and weakened immune response to upper respiratory bugs.',
    ],
    foodSourcesSorted: [
      {
        name: 'Guava',
        serving: '1 cup (165g)',
        amount: '377 mg',
        dailyValuePercentage: 419,
        category: 'fruit',
        dietaryTags: ['vegan', 'vegetarian', 'gluten_free'],
        notes: 'Highest common fruit concentration, beating oranges by 4x.',
      },
      {
        name: 'Yellow / Red Bell Pepper (Raw)',
        serving: '1 large pepper (186g)',
        amount: '342 mg',
        dailyValuePercentage: 380,
        category: 'vegetable',
        dietaryTags: ['vegan', 'vegetarian', 'gluten_free'],
        notes: 'Much richer in vitamin C than citrus fruits without acidity.',
      },
      {
        name: 'Kiwifruit (Raw, Green/Gold)',
        serving: '2 medium kiwis (140g)',
        amount: '137 mg',
        dailyValuePercentage: 152,
        category: 'fruit',
        dietaryTags: ['vegan', 'vegetarian', 'gluten_free'],
        notes: 'Also supplies digestive enzymes (actinidin).',
      },
      {
        name: 'Broccoli (Steamed/Raw)',
        serving: '1 cup chopped (90g)',
        amount: '81 mg',
        dailyValuePercentage: 90,
        category: 'vegetable',
        dietaryTags: ['vegan', 'vegetarian', 'gluten_free'],
        notes: 'Steam lightly for 3 minutes to avoid heat degradation.',
      },
      {
        name: 'Strawberries (Fresh)',
        serving: '1 cup halves (152g)',
        amount: '89 mg',
        dailyValuePercentage: 99,
        category: 'fruit',
        dietaryTags: ['vegan', 'vegetarian', 'gluten_free'],
        notes: 'High in anthocyanin antioxidants.',
      },
      {
        name: 'Navel Orange',
        serving: '1 medium orange (140g)',
        amount: '70 mg',
        dailyValuePercentage: 78,
        category: 'fruit',
        dietaryTags: ['vegan', 'vegetarian', 'gluten_free'],
        notes: 'Classic dietary source; eating whole orange preserves bioflavonoids and fiber.',
      },
    ],
    consumptionAndBioavailabilityAdvice: [
      'Heat & Light Sensitive: Prolonged boiling leaches vitamin C into cooking water. Enjoy fruits and veggies raw, lightly steamed, or microwaved.',
      'Smokers require at least 35 mg extra daily due to elevated oxidative stress and free radical clearance.',
    ],
  },
];

export function findNutrientProfile(query: string): NutrientProfile | null {
  if (!query) return null;
  const q = query.toLowerCase().trim();
  const normalized = q.replace(/vitamine/g, 'vitamin').replace(/[^a-z0-9]/g, '');

  for (const nutrient of NUTRITION_KNOWLEDGE_BASE) {
    if (
      nutrient.aliases.some((alias) => {
        const aliasLower = alias.toLowerCase();
        const aliasNorm = aliasLower.replace(/[^a-z0-9]/g, '');
        return q.includes(aliasLower) || normalized.includes(aliasNorm);
      })
    ) {
      return nutrient;
    }
  }
  return null;
}
